services:
  frontend:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      DATABASE_URL:            mysql2://dev_user:123456@db/my_database?encoding=utf8mb4&collation=utf8mb4_unicode_ci
      LANG:                    en_US.UTF-8
      RAILS_ENV:               development
      RACK_ENV:                development
      RACK_TIMEOUT_LOG_LEVEL:  DEBUG
    ports:
      - "8080:80"

  backend:
    build: ../backend
    command: apache2-foreground
    environment:
    ports:
      - "8081:80"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_database
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: 123456

volumes:
    db_data:
